sycl_EXTERNAL_DEPENDS := TBB SYCL
SYCLCore_DEPENDS := Framework
PointsLoader_DEPENDS := Framework SYCLCore DataFormats SYCLDataFormats
PointsLoaderValidator_DEPENDS := Framework SYCLCore DataFormats SYCLDataFormats